root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
args_bin = []
bin = "./bin/everato"
cmd = "go build -o ./bin/everato -tags=dev ."
delay = 1000
exclude_dir = ["assets", "vendor", "testdata", "logs"]
exclude_file = []
exclude_regex = ["_test.go", ".log", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "html", "css"]
include_file = []
kill_delay = "0s"
log = "./logs/build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = [
    "templ generate",
    "./bin/tailwind -i ./styles/root.css -o ./public/css/styles.css",
]
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = "blue"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 8080
enabled = true
proxy_port = 9090

[screen]
clear_on_rebuild = false
keep_scroll = true
