services:
    api:
        build: .
        ports:
            - "8080:8080"
        env_file: .env
        depends_on:
            - kafka
            - postgres

    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: everato
            POSTGRES_USER: piush
            POSTGRES_PASSWORD: root_access
        ports:
            - "5432:5432"

    kafka:
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        depends_on:
            - zookeeper

    zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - "2181:2181"
